version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - ./client/src:/app/src
  client-tests:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes: 
      - /app/node_modules
      - ./client/src:/app/src
    command: ["npm", "run", "test"]
